export type LichenStructure = 'Crustose' | 'Foliose' | 'Fruticose';

export interface BreathRecording {
  duration: number; // in seconds
  intensity: number; // average level (0 to 100)
  pikes: number; // rhythmic intensity spikes
}

export interface ArchivalObservation {
  id: string;
  timestamp: number; // Unix timestamp in ms
  observationNumber: number;
  text: string;
}

export interface LichenOrganism {
  id: string; // unique identifier
  name: string; // unique taxonomic botanical name
  seed: number; // numeric seed for procedural rendering
  birthTime: number; // Unix timestamp in ms
  breathDuration: number; // cumulative exhalation duration in seconds
  breathIntensity: number; // average biometric intensity (0 to 100)
  breathRhythm: string; // textual description of rhythm (e.g., "Steady & Synced", "Saccadic Impulse", "Crescendo Flow")
  
  // Parameters derived from breath volatiles
  branchDensity: number; // 0.2 to 0.9
  baseColor: string; // primary lichen color hex
  accentColor: string; // secondary spore glow color hex
  growthDirection: number; // angle offset in radians
  glowIntensity: number; // float representing luminescence
  structure: LichenStructure; // biological lichen category
  
  // Custom features that unlock over time
  crystalsCount: number; // crystal formations
  fungalBlooms: number; // counts of companion fungal spore heads
  colorMutationOffset: number; // hue-shift degree as it adapts to time
  
  // AI observations generated by the Archivist
  observations: Array<ArchivalObservation>;
  memories: Array<{ // keep for backward compatibility if any old records exist
    text: string;
    timestamp: number;
  }>;
}
